# Generated by Django 4.2.1 on 2023-07-22 06:50

from django.db import migrations, models
import django.db.models.deletion
import su_staffs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dpet_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='DEPARTMENT ID')),
                ('dpet_name', models.CharField(max_length=255, verbose_name='DEPARTMENT NAME')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='SCHOOL ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='SCHOOL NAME')),
            ],
        ),
        migrations.CreateModel(
            name='SU_Staff',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='STAFF ID')),
                ('name', models.CharField(max_length=256, verbose_name='STAFF NAME')),
                ('title', models.CharField(choices=[('', ''), ('Prof.', 'Prof.'), ('Assoc. Prof.', 'Assoc. Prof.'), ('Assoc. Prof. Dr', 'Assoc. Prof. Dr'), ('Prof. Datuk Dr', 'Prof. Datuk Dr'), ('Prof. Datin Dr', 'Prof. Datin Dr'), ('Dr', 'Dr'), ('Mr', 'Mr'), ('Ms', 'Ms')], default='', max_length=20, verbose_name='TITLE')),
                ('status', models.BooleanField(default=True, verbose_name='STATUS')),
                ('author_name', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='AUTHOR NAME')),
                ('dpet_id', models.ForeignKey(db_column='dpet_id', default=su_staffs.models.get_default_dept, on_delete=django.db.models.deletion.CASCADE, to='su_staffs.department')),
            ],
            options={
                'verbose_name': 'SU Staff',
                'verbose_name_plural': 'SU Staffs',
            },
        ),
    ]
