# Generated by Django 4.2.1 on 2023-07-22 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import su_staffs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('su_staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='su_staff',
            name='user',
            field=models.OneToOneField(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='school_id',
            field=models.ForeignKey(db_column='school_id', default=su_staffs.models.get_default_school, on_delete=django.db.models.deletion.CASCADE, to='su_staffs.school'),
        ),
    ]
