# Generated by Django 4.2.1 on 2023-07-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('project_code', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='PROJECT CODE')),
                ('project_title', models.CharField(max_length=256, verbose_name='PROJECT TITLE')),
                ('grant_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='GRANT NAME')),
                ('project_start_date', models.DateField(blank=True, max_length=256, null=True, verbose_name='PROJECT START DATE')),
                ('project_end_date', models.DateField(blank=True, max_length=256, null=True, verbose_name='PROJECT END DATE')),
                ('amount_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='AMOUNT AWARDED (RM)')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='SPONSOR ID')),
                ('sponsor_name', models.CharField(max_length=256, verbose_name='SPONSOR NAME')),
                ('sponsor_category', models.CharField(choices=[('International', 'International'), ('National', 'National'), ('Collaboration', 'Collaboration'), ('Private', 'Private')], default='National', max_length=20, verbose_name='SPONSOR CATEGORY')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
    ]
