# Generated by Django 4.2.1 on 2023-07-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('su_staffs', '0001_initial'),
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='grant_su_staff', to='su_staffs.su_staff'),
        ),
        migrations.AddField(
            model_name='grant',
            name='sponsor',
            field=models.ForeignKey(blank=True, db_column='sponsor_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='grants.sponsor'),
        ),
        migrations.AddField(
            model_name='grant',
            name='su_staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='su_staffs.su_staff'),
        ),
    ]
