# Generated by Django 4.2.1 on 2023-07-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('su_staffs', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='su_staff',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='publications', to='su_staffs.su_staff'),
        ),
        migrations.AddField(
            model_name='publication',
            name='wos_publication',
            field=models.ForeignKey(blank=True, db_column='wos_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.wospublication'),
        ),
    ]
