# Generated by Django 4.2.1 on 2023-07-22 06:58
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial'),
    ]

    operations = [TrigramExtension()
    ]
